Z score library added
Welthungerhilfe/cgm-ml pull request #107
Opened 2020-10-05 12:04 UTC by prajurock

**Task Completed By Library**
Z score of weight vs Age
Z score of Height vs Age
Z score of Weight vs length

Malnutrition class of children (Verified by Jana(ACF) and Shivangi)

Z score with library

Growth chart for Nutritionist
a) Growth chart of Weight vs Age
b) Growth chart of Height vs Age
c) Growth chart of Weight vs Height

_Unit Test Case written_

TODO:
Update Readme in Pypi
Code feedback

2020-10-05 12:21 UTC, prajurock commented
https://peditools.org/growthwho/
Tool for z score

2020-10-05 12:30 UTC, prajurock commented
[Malnutrition Classification.docx](https://github.com/Welthungerhilfe/cgm-ml/files/5327257/Malnutrition.Classification.docx)
![Flow chart for Pop up msg - Page 2 (1)](https://user-images.githubusercontent.com/26791135/95079089-c680fa00-0733-11eb-8a5c-fe82e3a44240.jpeg)
![CGM Flow Chart (1)](https://user-images.githubusercontent.com/26791135/95079094-c7b22700-0733-11eb-874e-9b92f9d9c83a.jpeg)

2020-10-05 13:42 UTC, markus-hinsche requested changes
Thanks for the PR. I made some comments, mostly about formatting. Feel free to request a review again once you tackled the comments

2020-10-05 13:42 UTC, markus-hinsche commented on src/common/zscore/LICENSE
> +Copyright (c) UNICEF and individual contributors.
This repository already has a license. Should we remove this? Or how is this license related?

2020-10-05 13:42 UTC, markus-hinsche commented on src/common/zscore/README
> +z-scores of anthropometric measurements of children below 5 years  based on WHO
Please write a sentence, because this is easier to understand

2020-10-05 13:42 UTC, markus-hinsche commented on src/common/zscore/README
> +
Please use the proper markdown syntax for code: https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

2020-10-05 13:42 UTC, markus-hinsche commented on .gitignore
> +.DS_Store
Please ensure that the last line of code files is empty

2020-10-05 13:42 UTC, markus-hinsche commented on src/common/zscore/ZscoreWeb/script.py
> +   return render_template('first.html',user_image=file_path)
Please run flake8 to improve code style, e.g. like this: `flake8 src/common/zscore/`

2020-10-05 13:42 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/ConvertableData/data_convestion_toolkit.py
> +    df = pd.read_csv(percentaile_data_path, sep='\t')
```suggestion
    df = pd.read_csv(percentile_data_path, sep='\t')
```

2020-10-05 13:42 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/ConvertableData/data_convestion_toolkit.py
> +    value = []
Is there a more specific name instead of `value`?

2020-10-06 07:38 UTC, markus-hinsche requested changes
I added a few more comments and suggestions

2020-10-06 07:38 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/test_cgmzscore.py
> +            assert True
remove because has no effect

2020-10-06 07:38 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/test_cgmzscore.py
> +import pytest
```
"""Found code at http://skdjfksdj.com"""
```

2020-10-06 07:38 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/test_cgmzscore.py
> +            sex = 'F'
```suggestion
        sex = 'M' if df['GENDER'][i] == 1 else 'F'
```

2020-10-06 07:38 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/test_cgmzscore.py
> +
```
def check_null():
    return pd.isnull(df.loc[i, 'HEIGHT']) or pd.isnull(df.loc[i, 'WEIGHT']) or pd.isnull(df.loc[i, '_agedays']) or pd.isnull(df.loc[i, '_ZWFL'] or df.loc[i, '_agedays'] == 0))
```

2020-10-06 07:38 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/test_cgmzscore.py
> +        if(pd.isnull(df.loc[i, 'HEIGHT']) or pd.isnull(df.loc[i, 'WEIGHT']) or pd.isnull(df.loc[i, '_agedays']) or pd.isnull(df.loc[i, '_ZWFL'] or df.loc[i, '_agedays'] == 0)):
```suggestion
        if check_null(): 
```

2020-10-06 07:38 UTC, markus-hinsche commented on src/common/zscore/cgmzscore/ConvertableData/data_convestion_toolkit.py
> +    percentile_data_path = REPO_DIR + '/ConvertableData/' + percentile_data_path
```suggestion
    percentile_data_path = REPO_DIR / 'ConvertableData' / percentile_data_path
```

2020-10-06 07:39 UTC, markus-hinsche commented on src/common/zscore/README.rst
> +    v = Calculator().zScore_wfa(weight="7.853",muac="13.5",age_in_days='16',sex='M',height='73')
```suggestion
```python
from cgmzscore import Calculator
v = Calculator().zScore_wfa(weight="7.853",muac="13.5",age_in_days='16',sex='M',height='73')
```
```

2020-10-08 04:40 UTC, merged