Zscore pipeline
Welthungerhilfe/cgm-ml pull request #113
Opened 2020-10-09 03:43 UTC by prajurock

2020-10-19 15:22 UTC, markus-hinsche requested changes
There are a lot of changes that don't belong to this PR.

2020-10-19 15:22 UTC, markus-hinsche commented on .github/pull_request_template.md
> +# Description
This is already merged to master. Please git rebase this branch onto master to only show the files that belong to this PR.

2020-10-20 09:35 UTC, markus-hinsche requested changes

2020-10-20 09:35 UTC, markus-hinsche commented on src/common/zscore/azure-pipelines.yml
> +    pip install numpy==1.19.1 tensorflow==2.3.0 azureml-sdk[notebooks,automl]==1.13.0 glob2==0.7 imgaug==0.4.0 flake8==3.8.4 pytest pytest-azurepipelines
Only install what you need, e.g. we don't use tensorflow here. 
Please check for the other dependencies mentioned here.

2020-10-20 09:35 UTC, markus-hinsche commented on src/common/zscore/azure-pipelines.yml
> +# Python package
The checks are hard to distinguish in github (see picture). 

![image](https://user-images.githubusercontent.com/1809832/96568264-0addcf80-12c8-11eb-9bd8-a2da028fb159.png)

Can we rename the zscore pipelines so that their name contains "zscore"?

2020-10-20 13:07 UTC, prajurock commented on src/common/zscore/azure-pipelines.yml
> +# Python package
welhungerhilfe-cgm-z-score

2020-10-20 13:42 UTC, markus-hinsche approved these changes
LGTM

Make sure the build pipelines are succeeding, and then this is ready to merge 👍

2020-10-20 14:07 UTC, merged