Move code from old repository
Welthungerhilfe/cgm-ml pull request #119
Opened 2020-10-14 14:46 UTC by prajurock

# Description

1. Standing/laying classifier for filtering the bad data

User story # [()](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/59)

# How Has This Been Tested?

No test is written

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2020-10-20 14:28 UTC, gangooteli commented on src/analyses/reliability/Standing-laying/utils.py
> +            if '_100_' in file or '_101_' in file or '_102_' in file:
Defind scancode dictionary variable instead on hardcoded values

2020-10-20 14:54 UTC, gangooteli requested changes
Please make necessary changes

2020-10-20 14:54 UTC, gangooteli commented on src/analyses/reliability/Standing-laying/utils.py
> +            if '_200_' in file or '_201_' in file or '_202_' in file:
Same changes for here

2020-10-20 14:54 UTC, gangooteli commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/model.py
> +    if dropout is True:
if dropout:

will also work

2020-10-20 14:54 UTC, gangooteli commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/test/test_train.py
> +    paths = ['/Users/prajwalsingh/cgm-ml-service/data/anon-rgb-classification/test/laying/rgb_1597851643-23im8oux3j_1597851643547_202_330741.97858975903.jpg']
why are we using this hardcoded value of your machine. What if someone else will use this code?

2020-10-20 14:54 UTC, gangooteli commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/test/test_train.py
> +    paths = ['/Users/prajwalsingh/cgm-ml-service/data/anon-rgb-classification/test/standing/rgb_1583438117-71v1y4z0gd_1592711198959_100_74914.611084559.jpg']
Above comment applies for here.

2020-10-20 14:54 UTC, gangooteli commented on src/analyses/reliability/Standing-laying/Evaluation_standing_laying.ipynb
> +    "model = load_model(REPO_DIR / 'src' / 'common' / 'eval' / 'logs'/ 'q4-rgb-plaincnn-classifaction-standing-lying-8k' / 'run_27' / 'best_model.h5') \n",
I am not sure, How you are getting the model. Are you downloading manually from the experiment. How one will use this script without download script.

2020-10-20 15:05 UTC, markus-hinsche reviewed
Great results on the standing/laying classifier. I added some more comments, because I think this code can be very helpful for the project in the future so I think it is worth taking a bit more time to make the code look even nicer :)

2020-10-20 15:05 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/data_preparation/data_preparation.py
> +    os.mkdir(LAYINGING_PATH)
There might be some more modern (Py 3.6) way to write this: https://stackoverflow.com/questions/273192/how-can-i-safely-create-a-nested-directory

2020-10-20 15:05 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/data_preparation/data_preparation.py
> +print("Shape of artifacts in ML database" + artifacts.shape)
```suggestion
print("Shape of artifacts in ML database: " + artifacts.shape)
```

2020-10-20 15:05 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/data_preparation/data_preparation.py
> +print(artifacts['label'].value_counts())
Please put logic into a function

2020-10-20 15:05 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/data_preparation/data_preparation.py
> +def find_artifacts_by_label(label, start_point, end_point, artifacts):
This comment looks like it doesn't belong. It wants to be a docstring, right?

```suggestion
def find_artifacts_by_label(label, start_point, end_point, artifacts):
   """Copy the artifacts from one folder to another
        and rotating the laying child by 90 anti-clockwise and
        standing child by 270 anti-clockwise
   """
```

2020-10-20 15:05 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/data_preparation/data_preparation.py
> +            im.save(dst)
This looks like a lot of code duplication, because `if` and `elif` are very similar

2020-10-20 15:31 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/test/test_train.py
> +from train import process_path
Please ensure that the tests are executed in the CI pipeline

2020-10-21 01:09 UTC, prajurock commented
Thanks, @gangooteli  @markus-hinsche . I will do the changes.

2020-10-21 01:13 UTC, prajurock commented on src/analyses/reliability/Standing-laying/Evaluation_standing_laying.ipynb
> +    "model = load_model(REPO_DIR / 'src' / 'common' / 'eval' / 'logs'/ 'q4-rgb-plaincnn-classifaction-standing-lying-8k' / 'run_27' / 'best_model.h5') \n",
Yes, the Model size is very big(around 200Mb). And azure gives 120s for downloading which is not possible for my internet. What you will suggest?

2020-10-21 08:56 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/train.py
> +model.fit(
I wonder if we should reduce the learning rate during fine-tuning (e.g. see https://towardsdatascience.com/how-to-fine-tune-your-neural-network-for-your-data-image-classification-d0f01c92300b#12cd)

2020-11-04 06:56 UTC, prajurock commented
flake8 test fail in pipelines but it was not part of my code, so I am not changing anything in this PR

2020-11-04 10:56 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/train.py
> +optimizer = tf.keras.optimizers.RMSprop(learning_rate=CONFIG.LEARNING_RATE)
No, validation accuracy reaches nearly 99% is the reason

2020-11-04 10:58 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/model.py
> +base_model = keras.applications.Xception(
done

2020-11-04 10:59 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/train.py
> +model.fit(
I can try this but still, the same Answer-Val accuracy is 99%

2020-11-04 11:08 UTC, prajurock commented on src/analyses/reliability/Standing-laying/utils.py
> +    import re
Import statement shifted to the top

2020-11-04 11:10 UTC, prajurock commented on src/analyses/reliability/Standing-laying/utils.py
> +def find_closest(A, target):
Done. Change the variable name

2020-11-04 11:11 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/train.py
> +#    print("created folder : ", save_dir)
Remove these lines

2020-11-04 11:12 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/train.py
> +AUTOTUNE = tf.data.experimental.AUTOTUNE
Autotune is used below
`dataset_norm = dataset_norm.prefetch(tf.data.experimental.AUTOTUNE)
`

2020-11-04 11:13 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/test/test_train.py
> +import tensorflow as tf
This really helps. Make code looks good

2020-11-04 11:13 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/model.py
> +def fine_tuning(layer_name):
yes done

2020-11-04 11:13 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/model.py
> +def fine_tuning(layer_name):
yes done

2020-11-04 11:15 UTC, prajurock commented on src/analyses/reliability/Standing-laying/utils.py
> +    return return_timestamp  # index error? IndexError
Not sure

2020-11-04 11:31 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/data_preparation/data_preparation.py
> +    os.mkdir(LAYINGING_PATH)
`os.makedirs(PARENT_DIRECTORY+'standing_laying_v1.0/train/standing', exist_ok=True)
os.makedirs(PARENT_DIRECTORY+'/standing_laying_v1.0/train/laying', exist_ok=True)`

code added

2020-11-04 11:33 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/data_preparation/data_preparation.py
> +    os.mkdir(LAYINGING_PATH)
`os.makedirs(PARENT_DIRECTORY+'standing_laying_v1.0/train/standing', exist_ok=True)
os.makedirs(PARENT_DIRECTORY+'/standing_laying_v1.0/train/laying', exist_ok=True)`

code added

2020-11-04 11:33 UTC, prajurock commented on src/analyses/reliability/Standing-laying/utils.py
> +            if '_200_' in file or '_201_' in file or '_202_' in file:
directory added

2020-11-04 11:33 UTC, prajurock commented on src/analyses/reliability/Standing-laying/utils.py
> +            if '_100_' in file or '_101_' in file or '_102_' in file:
dictionary

2020-11-04 11:34 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/test/test_train.py
> +    paths = ['/Users/prajwalsingh/cgm-ml-service/data/anon-rgb-classification/test/laying/rgb_1597851643-23im8oux3j_1597851643547_202_330741.97858975903.jpg']
removed this

2020-11-04 11:34 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/test/test_train.py
> +    paths = ['/Users/prajwalsingh/cgm-ml-service/data/anon-rgb-classification/test/standing/rgb_1583438117-71v1y4z0gd_1592711198959_100_74914.611084559.jpg']
done

2020-11-05 09:50 UTC, markus-hinsche requested changes

2020-11-05 09:50 UTC, markus-hinsche commented on src/analyses/reliability/Standing-laying/utils.py
> +    # A must be sorted
```suggestion
```

2020-11-05 09:50 UTC, markus-hinsche commented on src/analyses/reliability/Standing-laying/utils.py
> +def download_model(ws, EXPERIMENT_NAME, RUN_ID, INPUT_LOCATION, OUTPUT_LOCATION):
Local variables should be lowercase. 
- EXPERIMENT_NAME -> experiment_name
- RUN_ID -> run_id
- ...

Please check for more occurrences in this PR.

2020-11-05 09:50 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/model.py
> +            layer.trainable = False
I think this code is setting not only one layer but all layers after this. 
This might not be what this function signature suggests.

2020-11-05 09:50 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/test/test_train.py
> +import sys
Why is this module called `test_train.py`?
Should we call it `test_preprocessing.py`

2020-11-05 09:50 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-lying/src/train.py
> +AUTOTUNE = tf.data.experimental.AUTOTUNE
No, `tf.data.experimental.AUTOTUNE` is used below but `AUTOTUNE` is not used

2020-11-05 10:25 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/test/test_train.py
> +import sys
Yes.

2020-11-05 10:33 UTC, prajurock commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/model.py
> +            layer.trainable = False
set_trainable_below_layers. This looks good?

2020-11-05 10:33 UTC, prajurock commented on src/analyses/reliability/Standing-laying/utils.py
> +def download_model(ws, EXPERIMENT_NAME, RUN_ID, INPUT_LOCATION, OUTPUT_LOCATION):
done

2020-11-05 10:51 UTC, markus-hinsche commented on src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/model.py
> +            layer.trainable = False
Well, it is ok for now. This code is still quite experimental, so not everything has to be perfect

2020-11-05 10:52 UTC, markus-hinsche approved these changes
LGTM

2020-11-05 10:58 UTC, merged