Rgbd multi
Welthungerhilfe/cgm-ml pull request #134
Opened 2020-10-27 08:33 UTC by whyshreddy

# Description

edited readme

User story # (US link)
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/175

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2020-10-27 09:45 UTC, markus-hinsche requested changes
Hi Vaishnavi, thanks for submitting your code. 
I see that this was a lot of work so thanks for putting in the effort. 

I left a few comments that you could address, also we can make the style checker happy. 

After that you can re-assign me again to make a second review. Please tell me in the PR description how I can try this out (which dataset to download, which command to run exactly).

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/.gitignore
> +# These are some examples of commonly ignored file patterns.
We already have a .gitignore file in the repo's root, so I think we can remove this file.

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/README.md
> +rgbd.py [-h] [--input inputpath] [--output outputpath] optional: [--mounted if using the input as the mounted datastore of qr codes]  [--w specifying number of workers]
```suggestion
python rgbd.py [-h] [--input inputpath] [--output outputpath] optional: [--mounted if using the input as the mounted datastore of qr codes]  [--w specifying number of workers]
```

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/README.md
> +python rgbd.py --input [/mnt/cgmmlprod/cgminbmzprod_v5.0/] --output [/mnt/preprocessed/rgbd56k/] --mounted --w [20]
Can we remove the square brackets? This is an example so I think we don't need them

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/cgm_fusion/fusion.py
> +import datetime
`datetime` is a standard library so you can put it in the first block of imports

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/cgm_fusion/fusion.py
> +def fuse_rgbd(calibration_file,pcd_file,image, seg_path=0):
This function is quite long. You can split it into multiple functions to make it more readable.

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/cgm_fusion/utility.py
> +        pass
Should we log an error?
Can you add the specific exception that you will catch here?

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/cgm_fusion/utility.py
> +    #calibration_file =  '/whhdata/calibration.xml'
I think we can remove this line. 

Check also in other places if we can remove commented code that we don't need anymore. 

This will make the code more readable

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/requirements.txt
> +psycopg2-binary
I suggest to add this to the `requirements.txt` in the repo's root

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/rgbd.py
> +def find_closest(A, target):
I am not sure what `A` is. Can we find a better variable name, so it is more clear?

2020-10-27 09:45 UTC, markus-hinsche commented on src/common/rgbd_toolkit/rgbd.py
> +def process_pcd(norm_pcd_time,process_index=0):
This function is quite long. You can split it into multiple functions to make it more readable.

2020-10-28 10:08 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +rgbd.py [-h] [--input inputpath] [--output outputpath] optional: [--mounted if using the input as the mounted datastore of qr codes]  [--w specifying number of workers]
done

2020-10-28 10:09 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +python rgbd.py --input [/mnt/cgmmlprod/cgminbmzprod_v5.0/] --output [/mnt/preprocessed/rgbd56k/] --mounted --w [20]
done

2020-10-28 10:24 UTC, whyshreddy commented on src/common/rgbd_toolkit/cgm_fusion/fusion.py
> +def fuse_rgbd(calibration_file,pcd_file,image, seg_path=0):
made function projectPoints() whose purpose would be to return im_coords of points-done

2020-10-28 10:25 UTC, whyshreddy commented on src/common/rgbd_toolkit/cgm_fusion/fusion.py
> +import datetime
removed it as i used to only measure how much time fuse_rgbd takes-done

2020-10-28 10:35 UTC, whyshreddy commented on src/common/rgbd_toolkit/cgm_fusion/utility.py
> +        pass
removed the try except as there wont be errors expected-done

2020-10-28 10:36 UTC, whyshreddy commented on src/common/rgbd_toolkit/cgm_fusion/utility.py
> +    #calibration_file =  '/whhdata/calibration.xml'
done

2020-10-28 10:40 UTC, whyshreddy commented on src/common/rgbd_toolkit/requirements.txt
> +psycopg2-binary
done

2020-10-28 10:47 UTC, whyshreddy commented on src/common/rgbd_toolkit/.gitignore
> +# These are some examples of commonly ignored file patterns.
done

2020-10-28 11:33 UTC, whyshreddy commented on src/common/rgbd_toolkit/rgbd.py
> +def find_closest(A, target):
done

2020-10-28 17:26 UTC, whyshreddy commented on src/common/rgbd_toolkit/rgbd.py
> +def process_pcd(norm_pcd_time,process_index=0):
doone

2020-10-29 07:26 UTC, whyshreddy commented
Steps to test/execute:
1. Doownload the mini dataset as your input dir :
`from azureml.core import Workspace, Dataset

subscription_id = '9b82ecea-6780-4b85-8acf-d27d79028f07'
resource_group = 'cgm-ml-prod'
workspace_name = 'cgm-azureml-prod'

workspace = Workspace(subscription_id, resource_group, workspace_name)

dataset = Dataset.get_by_name(workspace, name='anon-bmz-mini')
dataset.download(target_path='.', overwrite=False)`

2. Make an output dir where you want the RGBD to be made.
3. use : python rgbd.py --input [input dir] --output [output dir] --w [no. of workers to use]

PS: refer to readme for more details.

2020-10-29 16:02 UTC, markus-hinsche reviewed
I did a second round of review. 

There are a few things (a lot less than first time) things in the code that can be improved. Since a lot of this code has been moved from `old/` these are often not generated by you. 

That being said, I would like to understand the output better. When I ran this I got a colorful image, however I expected a 4 channel numpy array, e.g. in pickle format.

Thanks for all the efforts

2020-11-02 05:14 UTC, whyshreddy commented on src/common/rgbd_toolkit/cgm_fusion/utility.py
> +    get_viz_channel(ply_path, channel=Channel.red, output_path="/tmp/red.png")
done

2020-11-02 05:14 UTC, whyshreddy commented on src/common/rgbd_toolkit/cgm_fusion/fusion.py
> +    im_coords, _ = cv2.projectPoints(pcd_points, r_vec,
done

2020-11-02 05:14 UTC, whyshreddy commented on src/common/rgbd_toolkit/get_timestamps.py
> +    if (len(timestamps) == 0):
done

2020-11-02 05:15 UTC, whyshreddy commented on src/common/rgbd_toolkit/get_timestamps.py
> +    import re
done

2020-11-02 05:41 UTC, whyshreddy commented on src/common/cgmcore/imageprocessing.py
> +def find_faces(image, mark_faces=False):
done

2020-11-02 05:41 UTC, whyshreddy commented on src/common/cgmcore/modelutils.py
> +    if use_lstm is True:
done

2020-11-02 05:41 UTC, whyshreddy commented on src/common/cgmcore/pcd_to_pickle.py
> +    return
done

2020-11-02 05:41 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +python rgbd.py [-h] [--input inputpath] [--output outputpath] optional: [--mounted if using the input as the mounted datastore of qr codes]  [--w specifying number of workers]
done

2020-11-02 05:41 UTC, whyshreddy commented on src/common/rgbd_toolkit/rgbd.py
> +        i = i + 1
done

2020-11-02 05:45 UTC, whyshreddy commented on src/common/rgbd_toolkit/rgbd.py
> +    logging.info("total time took is" + str(diff))
i prefer logging too, but since RGBD.log  is a big log file, often for me to be aware of the processing time it took, I needed to keep loading the large log file and scroll down to see the amount of time it took for processing, so I am going to remove logging.

2020-11-02 05:45 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +```
done

2020-11-02 05:46 UTC, whyshreddy commented on src/common/cgmcore/preprocesseddatagenerator.py
> +        paths = [path for path in paths if os.path.isdir(path) is True]
doone

2020-11-02 05:46 UTC, whyshreddy commented on src/common/cgmcore/modelutils.py
> +        pass
done

2020-11-02 05:46 UTC, whyshreddy commented on src/common/cgmcore/imageprocessing.py
> +#import numpy as np
done

2020-11-02 06:54 UTC, whyshreddy commented on src/common/rgbd_toolkit/rgbd.py
> +                        help='the path to the input qrcode folder')
done

2020-11-02 06:55 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +```
please help me reproduce this error to be able to fix it. For eg: if this is on your vm, i could cd into your dir and execute the aboove command to stumble upon the same error.

2020-11-02 07:00 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +
these are RGBD images. The values of RGB are the depth values.

2020-11-02 08:01 UTC, markus-hinsche commented on src/common/rgbd_toolkit/README.md
> +
Let's talk about it

2020-11-02 08:02 UTC, markus-hinsche commented on src/common/rgbd_toolkit/README.md
> +```
Sure, let's talk about this

2020-11-02 11:09 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +2. usage:
done

2020-11-02 11:10 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +3. TODO add segmented rgbd
this would be new functionality..so my plan was to add it only after the review of the current functionality is done

2020-11-02 11:11 UTC, whyshreddy commented on requirements.txt
> +psycopg2-binary==2.8.6
i removed the binary one for now as i dont need to connect to the postgres db anymore

2020-11-02 11:49 UTC, markus-hinsche commented on src/common/rgbd_toolkit/README.md
> +3. TODO add segmented rgbd
I suggest to remove this line for now and make a user story for any follow up tasks

2020-11-02 17:04 UTC, whyshreddy commented on src/common/rgbd_toolkit/rgbd.py
> +
fixed os.path.isdir

2020-11-02 17:05 UTC, whyshreddy commented on src/common/rgbd_toolkit/README.md
> +```
lets get into a call regarding this please

2020-11-02 17:14 UTC, markus-hinsche commented on src/common/cgmcore/modelutils.py
> +    if use_lstm is True:
Please do this for all occurrences, not just this line

2020-11-02 17:19 UTC, whyshreddy commented on src/common/cgmcore/modelutils.py
> +    if use_lstm is True:
i did it for all occurrences, thanks to flake8

2020-11-04 10:07 UTC, whyshreddy commented on src/common/cgmcore/modelutils.py
> +    if use_lstm is True:
i will leave it at 
```suggestion
    if use_lstm is True:
```
as i would have to change 
```suggestion
    if use_lstm is False/None:
```
and I am just used to this style

2020-11-04 10:37 UTC, markus-hinsche commented on src/common/cgmcore/modelutils.py
> +    if use_lstm is True:
Sure, this is fine for now

2020-11-04 10:48 UTC, markus-hinsche approved these changes
Great initial work on RGBD!

I checked this PR again. 
I could try it out and saw that there is a 4-channel numpy array produced as output.

2020-11-05 09:44 UTC, prajurock requested changes

2020-11-05 09:44 UTC, prajurock commented on src/common/rgbd_toolkit/rgbd.py
> +    left = rgb[idx - 1]
Please sort the RGB otherwise it give correct corresponding for some and wrong for another

2020-11-06 14:19 UTC, merged