Neptune
Welthungerhilfe/cgm-ml pull request #136
Opened 2020-10-27 17:37 UTC by whyshreddy

# Description
Added neptune logging into train.py 
User story # (US link)
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/149

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X ] Test A -tested locally if neptune logging works

# Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2020-10-28 07:34 UTC, markus-hinsche requested changes
Thanks for submitting the PR. 

One problem that I see is that this PR changes 44 lines in `train.py`. This makes `train.py` more complicated.
I suggest to refactor such that I we only have to add 1 or 2 lines to an experiment to include neptune: We could put a util function into utils.py and call it in train.py s.t. train.py only has to add 1-2lines

2020-10-28 07:34 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +if os.path.exists(best_model_path):
Why do we only log the best model in neptune after the training is finished?
Can we use a Callback to do it whenever there is a new model?

2020-10-28 07:34 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +training_params = CONFIG
Can we  put this line closer to it's usage for more readability?

2020-10-28 07:34 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +# Pushes metrics and losses into the run on Neptune
I don't understand what this comment belongs to. I suggest to not add newlines after a comment for better readability.

2020-10-29 08:39 UTC, AI-Guru commented
I would suggest putting the NeptuneLogger into a standalone module for reuse. Also the whole neptune.create_experiment(...) business could go into the constructor of the NeptuneLogger. I think this is what Markus also would like.

2020-11-12 17:08 UTC, markus-hinsche commented
Temporarily closing due to inactivity

2020-11-12 17:08 UTC, closed without merging