Pksingh multimodel evaluation
Welthungerhilfe/cgm-ml pull request #208
Opened 2020-12-08 06:27 UTC by prashant905

# Description

The branch was used to add the functionlit of multimodel evaluation and combining the  multiple csv of different models into 
a single csv file.

User story 584 (https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/584)

# How Has This Been Tested?

A new function is added to the pipeline combine_result.py. The pipeline ran successfully and the combined result CSV was produced for multiple height models.

Wiki Link for the results that were produced using this pipeline:
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_wiki/wikis/ChildGrowthMonitor.wiki/149/Evaluation-of-ML-models-depthmaps-height-realworld

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2020-12-08 07:58 UTC, markus-hinsche commented
Feedback: When putting this model into the wiki, can we make clear which run it is? The format changed to what we had before

Before: (word `run` is mentioned)
![image](https://user-images.githubusercontent.com/1809832/101455873-80af0080-3933-11eb-8f6c-fd54ad2ebfa1.png)

Now: (word `run` is not mentioned)
![image](https://user-images.githubusercontent.com/1809832/101455807-683ee600-3933-11eb-9783-ff5513dbab7c.png)

2020-12-08 07:58 UTC, markus-hinsche commented
Maybe you can find a better PR name: "Pksingh multimodel evaluation" -> e.g. "Model evaluation on real-world data"

2020-12-08 07:59 UTC, markus-hinsche requested changes
I wrote a couple of comments, mainly to clarify what the intention of this PR is. 

I am not sure why some other model evaluations are removed.

2020-12-08 07:59 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> -
Please don't remove this line. 

There is an common ordering into 3 sections in the imports:
- 1st section: standard library
- 2nd section: 3rd party
- 3rd section: own code

see more occurrences in this PR

2020-12-08 07:59 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +    result_csv_path = RESULT_CONFIG.SAVE_PATH + MODEL_CONFIG.RUN_ID + '.csv'
Please use a format string, using `+` to concatenate seems quite oldschool and limits readability

2020-12-08 07:59 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
> +class dotdict(dict):
`qa_config_42c4ef33.py`: This config name is not really human-readible. Should we make it more something like:
`qa_config_height_realworlddata.py`
We can adjust existing configs accordingly

2020-12-08 07:59 UTC, markus-hinsche commented on src/common/evaluation/QA/test-pipeline.yml
> -      python eval_main.py --qa_config_module qa_config_height
Why was this removed?

2020-12-08 07:59 UTC, markus-hinsche commented on src/common/evaluation/QA/test-pipeline.yml
> +      python eval_main.py --qa_config_module qa_config_cb44f6db
I suggest to make an extra step for each of these evaluations

2020-12-08 07:59 UTC, markus-hinsche commented on src/common/evaluation/QA/test-pipeline.yml
> +
```suggestion
```

2020-12-08 16:52 UTC, prashant905 commented on src/common/evaluation/QA/test-pipeline.yml
> -      python eval_main.py --qa_config_module qa_config_height
For the latest run, I ran different height models (run_03 and run_04), so created a separate config file for those models and remove this one.

2020-12-08 17:00 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
> +class dotdict(dict):
The multiple config files could be of height models evaluated on real-world data ..so can't name every config the same.
qa_config_42c4ef33.py ..adopted this from their RUN_ID _q3-depthmap-plaincnn-height-95k_1597988908_42c4ef33_
So that we can identify the qa_config file

2020-12-08 18:07 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +    result_csv_path = RESULT_CONFIG.SAVE_PATH + MODEL_CONFIG.RUN_ID + '.csv'
Done

2020-12-08 18:10 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> -
Done

2020-12-08 18:36 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> -
Please only write `Done` when the changes are pushed to GitHub. From what I can see, this is not Done yet. Probably not yet pushed

2020-12-10 20:12 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
> +    __delattr__ = dict.__delitem__
[nit] Elsewhere we are using bunch instead of dotdict now

2020-12-10 20:12 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/utils.py
> +    csv_file = "{}{}{}{}".format(CSV_OUT_PATH, '/', RUN_ID, '.csv')
Modern format strings are more readable 
```suggestion
    csv_file = f"{CSV_OUT_PATH}/{RUN_ID}.csv"
```

2020-12-10 20:12 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +    # run.download_file(result_csv_path, GET_CSV_FROM_EXPERIMENT_PATH)
Please don't keep uncommented code if possible. If this code is not used, let's remove it

2020-12-10 20:12 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +    # print("Result:", result)
For models where we don't combine the results, this would still be quite helpful, right?

2020-12-10 20:12 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/combine_results.py
> +    result_path = PATHS.get(model_measurement_type)
Should we validate the args so that we know that the model_measurement_type is in the PATHS dictionary keys

2020-12-10 20:12 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/combine_results.py
> +    PATHS = {
Please use lowercase when defining local variables

2020-12-11 11:44 UTC, markus-hinsche approved these changes
All comments were addressed. 

LGTM 👍

2020-12-11 13:51 UTC, merged