Filter evaluation added
Welthungerhilfe/cgm-ml pull request #212
Opened 2020-12-15 16:03 UTC by prajurock

# Description

Evaluation of the real-word dataset with standing/laying filter on the top

# Result
 With filter:

https://dev.azure.com/cgmorg/ChildGrowthMonitor/_wiki/wikis/ChildGrowthMonitor.wiki/149/Model-eval-depthmaps-height-real-world

https://dev.azure.com/cgmorg/ChildGrowthMonitor/_wiki/wikis/ChildGrowthMonitor.wiki/151/Model-eval-depthmaps-height-real-world-with-standing-laying-filter

User story # [160](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/160)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2020-12-17 12:26 UTC, markus-hinsche requested changes
Summary: This PR introduces a lot of code duplication. Can we think if it is possible to integrate this into the existing code?

2020-12-17 12:26 UTC, markus-hinsche commented on src/common/evaluation/QA/eval-depthmap-plaincnn-height-with-filter/auth.py
> +import argparse
`src/common/evaluation/QA/eval-depthmap-plaincnn-height-with-filter/` duplicates a lot of code that we have in `src/common/evaluation/QA/eval_depthmap_models` already

Instead I suggest to add a filter functionality:
- add a filter flag in config
- only a few additions to the code

2020-12-22 11:11 UTC, markus-hinsche reviewed
Prajwal. This looks a lot better, only very few files are changed now and the code duplication is gone. Nice!

I added some more suggestions. 

Most important before merging would be to run the azure pipeline to see if this actually works now.

2020-12-22 11:11 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py
> +    SWITCH='ON',  # 'OFF'
We can use a binary variable instead. 
```suggestion
    IS_ENABLED=True,
```

2020-12-22 11:11 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py
>  from bunch import Bunch
Please run this model evaluation with an azure pipeline and provide a link with the run in the PR description, so that the results/findings are documented

2020-12-22 11:11 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
> +    print(len(paths_evaluation))
To improve the readability of the code (`evaluate.py` is getting more and more complicated) we can move this logic into a function
```suggestion
    if FILTER_CONFIG.SWITCH == 'ON':
         new_paths_evaluation =  filter_dataset(paths_evaluation)
```

2020-12-22 11:11 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
>  # Function for loading and processing depthmaps.
Don't separate this comment from the function it belongs to

2020-12-22 11:11 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +                   output_location=str(temp_path) + '/' + FILTER_CONFIG.NAME)
The better usage of pathlib would be:

```suggestion
                   output_location=str(temp_path / FILTER_CONFIG.NAME))
```

2021-01-06 08:19 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
> +    if FILTER_CONFIG.SWITCH == True:
Notice that the parameter `SWITCH` does not exist anymore

```suggestion
    if FILTER_CONFIG.IS_ENABLED:
```

2021-01-08 08:01 UTC, markus-hinsche requested changes

2021-01-08 08:01 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
> +    NAME='anon-depthmap-rgb-timestamp',
Instead of changing an existing config, please consider creating a new config for your experiment and add this to `eval_configs.py`. 
This way you don't break existing configs

2021-01-08 10:56 UTC, markus-hinsche requested changes
One remaining problem is that you change existing qa_config files. Instead I suggest to not change our existing configuration and instead make a new config file for the analysis you want to add.

2021-01-08 10:56 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/utils.py
> +def process_image(data):
Could the function name be more specific? Why do we process in exactly this specific way?

2021-01-11 09:52 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +    FILTER_CONFIG = qa_config.FILTER_CONFIG
What happens if a qa_config file doesn't define a FILTER_CONFIG?

2021-01-11 10:20 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +    FILTER_CONFIG = qa_config.FILTER_CONFIG
yup. changes done

2021-01-11 10:23 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/src/utils.py
> +def process_image(data):
process the image in such a way that it get compatible with the standing/laying classification model.

2021-01-11 11:22 UTC, prajurock commented
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_build/results?buildId=2293&view=logs&j=3d42b299-58dd-525f-2f90-47c9dbee9ebd

2021-01-11 14:58 UTC, markus-hinsche requested changes

2021-01-11 14:58 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +        azureml._restclient.snapshots_client. SNAPSHOT_MAX_SIZE_BYTES = 500000000
```suggestion
        azureml._restclient.snapshots_client.SNAPSHOT_MAX_SIZE_BYTES = 500000000
```

2021-01-11 14:58 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_main.py
> +        FILTER_CONFIG = qa_config.FILTER_CONFIG
This is not a solid check: `args.qa_config_module == 'qa_config_filter'` (Hardcoding the module name is not a good solution, because there might be multiple modules in the future)

Please consider this alternative solution:
```python
FILTER_CONFIG = qa_config.FILTER_CONFIG if getattr(qa_config, 'FILTER_CONFIG', False) else None
```

2021-01-11 14:58 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_cb44f6db.py
> -
Why do you delete these lines? If there is no real reason, please revert this changes

2021-01-11 14:58 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/utils.py
> +        if qa_config_module == 'qa_config_filter':
Instead please check if `FILTER_CONFIG.IS_ENABLED`

2021-01-11 16:48 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
> +            depthmap, targets = pickle.load(open(path.numpy(), "rb"))
This if-else is duplicated. Please consider putting this into a function

2021-01-13 07:45 UTC, markus-hinsche reviewed
This PR improves. I looked at this PR again, please make sure all comments are addressed

2021-01-13 08:07 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
> +            depthmap, targets = pickle.load(open(path.numpy(), "rb"))
contains in different files so leaving for now

2021-01-13 08:08 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/src/utils.py
> +        if qa_config_module == 'qa_config_filter':
done

2021-01-13 08:08 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_cb44f6db.py
> -
undo

2021-01-13 08:08 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
> +    NAME='anon-depthmap-rgb-timestamp',
done

2021-01-13 08:23 UTC, markus-hinsche approved these changes
Looks good mostly now

2021-01-13 08:23 UTC, markus-hinsche commented on src/common/evaluation/QA/environment.yml
> +    - tensorflow==2.3.1
This should not be needed. We used tensorflow before and did not need to install it.

2021-01-13 08:32 UTC, prajurock commented on src/common/evaluation/QA/environment.yml
> +    - tensorflow==2.3.1
![image](https://user-images.githubusercontent.com/26791135/104426372-dc5e5080-55a7-11eb-9534-4c75c43d9cd9.png)
 was there

2021-01-13 08:33 UTC, merged