Enable eval pipeline in new tenant
Welthungerhilfe/cgm-ml pull request #236
Opened 2021-01-13 16:46 UTC by markus-hinsche

**Status quo:** We changed Service connection / Service Principle to the new tenant. Now the pipeline will always run in the new tenant. 

Changes:
- change experiment names and run ids so they get found in the new tenant

2021-01-15 14:33 UTC, prajurock requested changes

2021-01-15 14:33 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_filter.py
>      NAME='best_model.h5',
```suggestion
    NAME='best_model.ckpt',
```

2021-01-15 14:33 UTC, prajurock commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py
>      NAME='best_model.h5',
```suggestion
    NAME='best_model.ckpt',
```

2021-01-15 14:33 UTC, prajurock commented on src/common/evaluation/QA/environment.yml
> +  - setuptools=50.3.0
Why you add this?

2021-01-15 14:33 UTC, prajurock approved these changes

2021-01-15 14:35 UTC, markus-hinsche commented on src/common/evaluation/QA/environment.yml
> +  - setuptools=50.3.0
The PR description explains this.

2021-01-15 17:43 UTC, markus-hinsche commented on src/common/evaluation/QA/test-pipeline.yml
```suggestion

pr: none

```

2021-01-15 17:44 UTC, merged

2021-01-25 16:56 UTC, markus-hinsche commented
**height Dropout model**
old tenant(run17)
	min(val_mae): 2.21cm
new tenant(Run5):
	min(val_mae): 2.28cm