WIP 148 GitHub issue logging instead print
Welthungerhilfe/cgm-ml pull request #274
Opened 2021-02-17 13:27 UTC by jasminziegler

# Description
We want to replace all print statements with logging statements. 
Ideally: configurable logging from config file to perform settings on logging levels both for console and file log output individually.
First test on one file. After refinement of exact logging settings, roll out to entire repo.

User story # (US link) #148 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2021-02-17 13:57 UTC, markus-hinsche requested changes
Looks good overall, I still get an error, might be due to the location of the logging.conf file

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
>  print("Using {} files for validation.".format(len(paths_validate)))
Should we remove the print statement now that we have logging?

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +#print(len(qrcode_paths_training))
Let's delete instead of commenting to make the code less fuzzy

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +import logging.config
These imports should move up in the first import section (std lib)

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +logging.critical('critical ouch')
Before merging this debug code can be removed, but for now it helps me with debugging :)

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/logging.conf
> +[loggers]
Could we put this file into the root of this repository? `cgm-ml/src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/logging.conf` -> `cgm-ml/logging.conf`

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
>  print("\t" + "\n\t".join(qrcode_paths_training))
This should be logged to. The idea would be to not have print statements anymore in this code file

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
>  from config import CONFIG, DATASET_MODE_DOWNLOAD, DATASET_MODE_MOUNT
When running `python /Users/markus/Development/cgm/cgm-ml/src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py` I get an error

```
Traceback (most recent call last):
  File "/Users/markus/Development/cgm/cgm-ml/src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py", line 22, in <module>
    logging.config.fileConfig("logging.conf")
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

This seems related https://stackoverflow.com/questions/23161745/python-logging-file-config-keyerror-formatters

2021-02-17 13:57 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/logging.conf
> +[loggers]
I wonder if yaml is easier than conf file 

https://docs.python.org/3/library/logging.config.html

2021-02-18 08:39 UTC, jasminziegler commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/logging.conf
> +[loggers]
good call! on it

2021-02-18 10:45 UTC, jasminziegler commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/logging.conf
> +[loggers]
Is there a nicer way than this? 
logging.config.fileConfig("../../../../../../logging.conf")

2021-02-18 10:46 UTC, jasminziegler commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/logging.conf
> +[loggers]
Ok, let's try :-) Writing a yaml file now.

2021-02-18 10:55 UTC, jasminziegler commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
>  from config import CONFIG, DATASET_MODE_DOWNLOAD, DATASET_MODE_MOUNT
I had the same error when the file was in the wrong place/the link was wrong! thx for the notice

2021-02-18 12:38 UTC, jasminziegler commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
>  print("Using {} files for validation.".format(len(paths_validate)))
seems like I forgot to push this! sorry

2021-02-22 12:09 UTC, jasminziegler commented on logging.yaml
> +  lowdetail:
Reichen diese beiden Formatter aus bzw. sind sie mit den notwendigen Details versehen/fehlt etwas?

2021-02-22 12:10 UTC, jasminziegler commented on logging.yaml
> +
Brauchen wir hier noch mehr Details?

2021-02-22 12:41 UTC, markus-hinsche approved these changes
LGTM. Please remove some leftovers before merging (see my comments for details)

2021-02-22 12:41 UTC, markus-hinsche commented on logging.conf
> +[loggers]
Now that we have the .yaml, should we remove this?

2021-02-22 12:41 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +#try yaml
Please remove unused code

2021-02-22 12:41 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
>  #print(glob.glob(os.path.join(dataset_path, "*"))) # Debug
Please change the print statement to a logging statement (even though it is commented)

2021-02-22 12:41 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +logging.info('qrcode_paths: %d', len(qrcode_paths))  # warum hier len?????????????
Please remove your comment. This PR is not trying to make the outputs useful. Feel free to suggest a change in another PR

2021-02-22 12:41 UTC, markus-hinsche commented on src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
> +logging.critical('critical ouch')
This works great for me. I get all (except for `debug`) which is nice and as I expected

2021-02-25 09:14 UTC, merged

2021-02-26 16:34 UTC, markus-hinsche commented
👍