Compare inaccurate scans
Welthungerhilfe/cgm-ml pull request #281
Opened 2021-02-26 06:07 UTC by prashant905

# Description

The branch implements the functionality of comparing the inaccurate scans across two models. It finds out the common scans across two models which have greater error margin. 

User story #882  (https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/882/

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2021-02-26 07:46 UTC, markus-hinsche requested changes
Please go through the checklist in the PR description and check what you have done. 
The checks should pass and you should self-review the code. 
Please assign a reviewer again after this

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/combine_results.py
>  from glob2 import glob
Please revert the unwanted changes to this file

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/environment.yml
> +    - matplotlib-venn
Can we do without this library somehow? If we really need it then other requirements.txt files might have to be adjusted, but I would prefer plain matplotlib or writing text/table instead

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/eval_configs.sh
This file shouldn't have to change I think. I think you could revert your changes

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +ACC = 2
Can you rename this to ACCURACY_THRESHOLD ?

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +def filter_scans(dataframe: pd.DataFrame,accuracy: int):
Please type-annotate the return type as well if you annotate the parameter types

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +    error = dataframe[(dataframe['error'] >= accuracy) | (dataframe['error'] <= -accuracy)]
You can work with `abs(dataframe['error'])` to only need one comparison

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +def calculate_union(set1:set,set2:set):
What is the benefit of this function over just calling union directly?

2021-02-26 07:46 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +    Union_set = calculate_union(scan_sets[0],scan_sets[1])
please lowercase local variables

2021-03-02 07:46 UTC, prashant905 commented on src/common/evaluation/QA/environment.yml
> +    - matplotlib-venn
Removed this library and stick to simple report for now.

2021-03-02 07:46 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/eval_configs.sh
changesm reverted according to main branch

2021-03-02 07:47 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +def filter_scans(dataframe: pd.DataFrame,accuracy: int):
Done

2021-03-02 07:48 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +    error = dataframe[(dataframe['error'] >= accuracy) | (dataframe['error'] <= -accuracy)]
Done

2021-03-02 08:48 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +ACC = 2
Done

2021-03-02 21:19 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +def calculate_union(set1:set,set2:set):
This comment hasn't been addressed. What are your thoughts? @prashant905

2021-03-02 21:27 UTC, markus-hinsche requested changes
Too many questionmarks still. A lot of places got changed (e.g. EDA notebooks), but I don't understand why

2021-03-02 21:27 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +def frame_to_set(dataframe: pd.DataFrame) -> pd.DataFrame:
The return type looks wrong. I thing this should be a set

2021-03-02 21:27 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +def inaccurate_scans(file) -> pd.DataFrame:
Return type looks wrong

Parameter file is missing. 

`file` is a Python keyword, therefore the parameter could be renamed

2021-03-02 21:27 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +    for file in csv_files:
`file` is a Python keyword, therefore the variable could be renamed

2021-03-02 21:27 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +        scan_sets.append(frame_set)
[nit] This for loop could benefit from using list comprehension

2021-03-02 21:27 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
> +    sample_csv_file = f"{OUTPUT_CSV_PATH}/{RUN_ID}_scans.csv"
Please prefix with `scans_` to be consistent

```suggestion
    sample_csv_file = f"{OUTPUT_CSV_PATH}/scans_{RUN_ID}.csv"
```

2021-03-02 21:27 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/qa_config_filter.py
> +    DEBUG_RUN=True,
Please revert this change before merging

2021-03-02 21:27 UTC, markus-hinsche commented on src/common/evaluation/QA/test-pipeline.yml
> +
Why do we uncomment this?

2021-03-02 21:27 UTC, markus-hinsche commented on src/data_utils/dataset_EDA/anon-depthmap-95k/EDA_anon-depthmap-95k.ipynb
>   "cells": [
Why  are there changes to the EDA notebooks?

2021-03-03 14:19 UTC, prashant905 commented on src/common/evaluation/QA/eval_depthmap_models/inaccurate_scans.py
> +def calculate_union(set1:set,set2:set):
not much thought. trying to make code more modular(maybe overdoing it). Makes it extendable and more readable.  Seen this type implementation of making function even for the simplest of functionality.

2021-03-03 14:20 UTC, prashant905 commented on src/common/evaluation/QA/test-pipeline.yml
> +
Didn't need this part pipeline. hence commented it. revert back according to the master branch.

2021-03-03 14:22 UTC, prashant905 commented on src/data_utils/dataset_EDA/anon-depthmap-95k/EDA_anon-depthmap-95k.ipynb
>   "cells": [
make some changes in the EDA notebook to get some data for MS paper. did not push those changes and EDA notebook changed back according to the master branch now.

2021-03-03 14:29 UTC, markus-hinsche commented on src/data_utils/dataset_EDA/anon-depthmap-95k/EDA_anon-depthmap-95k.ipynb
>   "cells": [
I still see changes to EDA notebooks in this PR

2021-03-05 18:00 UTC, markus-hinsche reviewed
Almost ready for merge. Now there are a few comments mostly about naming things so this can be understood by a reader who is new to this topic

2021-03-15 08:31 UTC, markus-hinsche approved these changes
LGTM

2021-03-15 08:50 UTC, merged