WIP updated README file for EDA setup
Welthungerhilfe/cgm-ml pull request #294
Opened 2021-03-11 12:50 UTC by jasminziegler

# Description

Minor change in README instruction for setting up EDA notebooks.
During setup, I noticed that some commands are obsolete and added some details for clarity.

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] My Code is review by 1 People

2021-03-11 13:27 UTC, markus-hinsche requested changes
I don't understand yet how these changes improve our code

2021-03-11 13:27 UTC, markus-hinsche commented on src/data_utils/dataset_EDA/README.md
> -conda activate CGM_QA_Pipeline
We should still activate the correct environment here. This could work if you are in the right environment by coincidence, but this is a good reminder to check that you are in a certain env that is supposed to have a certain name

2021-03-11 13:27 UTC, markus-hinsche commented on src/data_utils/dataset_EDA/README.md
> +cd / # /*root*
Why is it better to put this in `/connection.cfg` instead of `/root/connection.cfg` ?

2021-03-11 13:27 UTC, markus-hinsche commented on src/data_utils/dataset_EDA/README.md
> +cd datasets
The next command (`cd realtime_evaluation`) will not work if we are not in the datasets dir

2021-03-12 08:23 UTC, jasminziegler commented on src/data_utils/dataset_EDA/README.md
> -conda activate CGM_QA_Pipeline
didn't work for me because I didn't know where to get the yml file from. Shanky suggested trying without these steps. 
So probably it worked by conincidence.
Maybe we should specify where to get the environment.yml file from or what to put in there. Can you help with this?

2021-03-12 08:42 UTC, markus-hinsche commented on src/data_utils/dataset_EDA/README.md
> -conda activate CGM_QA_Pipeline
https://github.com/Welthungerhilfe/cgm-ml/blob/main/src/common/evaluation/QA/environment.yml

2021-03-12 08:49 UTC, closed without merging