Rgdb dataset preparation
Welthungerhilfe/cgm-ml pull request #304
Opened 2021-03-19 09:27 UTC by prashant905

# Description

This branch is used for creating the RGBD dataset. There is EDA notebook for the dataset and  code that used for creating the dataset.

User story #395 (https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/395/)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] NO new test cases added. The code is run and the dataset was created successfully.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2021-03-22 15:08 UTC, markus-hinsche requested changes
Overall good work. I have suggestions for consistent naming of dataset and variables

2021-03-22 15:08 UTC, markus-hinsche commented on src/common/rgbd_dataset/rgbd_dataset.py
> +    json_path = f'{split_path}/targets.json'
[nit] I think a simple distinction can make code more readable:
- suffix `_fpath` for file paths
- suffix `_dir` for directory paths
- `f` for a file object/handle

```suggestion
    json_fpath = f'{split_path}/targets.json'
```

Consider applying this suggestion to other variables

2021-03-22 15:08 UTC, markus-hinsche commented on src/common/rgbd_dataset/rgbd_dataset.py
> +import zipfile
How did you check for outliers? What are the things you checked?

2021-03-22 15:08 UTC, markus-hinsche commented on src/common/rgbd_dataset/rgbd_dataset.py
> +TARGET_PATH = '/mnt/huawei_dataset/anon-rgbd-dataset'
Ideally the TARGET_PATH name is as similar to the dataset name as possible. Is it possible to rename this directory path to `anon-rgbd-5kscans`

2021-03-22 15:08 UTC, markus-hinsche commented on src/data_utils/dataset_EDA/anon-rgbd-5k/EDA_anon-rgbd-5k.ipynb
> +{
`EDA_anon-rgbd-5k.ipynb` -> `EDA_anon-rgbd-5kscans.ipynb`

2021-03-23 09:40 UTC, prashant905 commented on src/common/rgbd_dataset/rgbd_dataset.py
> +import zipfile
I used to  check for a maximum value of depth maps, when converting the data  from pcd to depthmaps in lenovo dataset. But this was already in depth format , here i did not perform that check.  Outlier regarding age to height , or for unusual age values are check during EDA analysis. I removed some data (around 1600 scans) but it will not be refelected in dataset preparation code.

2021-03-23 10:06 UTC, markus-hinsche commented on src/common/rgbd_dataset/rgbd_dataset.py
> +import zipfile
@jasminziegler works on checking unusual values, maybe she could perform the check on this dataset as well. To my knowledge, she checks:
- unusual pixel values (here it should be for depthmap, but also R, G and B)
- age
- weight
- height
- MUAC

2021-03-23 11:19 UTC, jasminziegler commented on src/common/rgbd_dataset/rgbd_dataset.py
> +import zipfile
correct! I finished age, weight, height and MUAC (where present) in 5 datasets and right now I am doing the checks for pixel values.

2021-03-23 16:40 UTC, markus-hinsche approved these changes
LGTM

Let's keep the code styling tricks in mind, would be great to apply this code styling techniques elsewhere in further PRs

2021-03-23 16:40 UTC, markus-hinsche commented on src/common/rgbd_dataset/rgbd_dataset.py
> +    source_pattern = f'{SOURCE_PATH}'
This variable is redundant now, you can just use `SOURCE_PATH`

2021-03-24 09:45 UTC, merged