Issue 328
Welthungerhilfe/cgm-ml pull request #339
Opened 2021-05-10 06:59 UTC by shanky0009

# Description

Make depthmap toolkit more pythonic
https://github.com/Welthungerhilfe/cgm-ml/issues/328

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2021-05-10 14:04 UTC, shanky0009 commented
- will add more unit tests in follow up PR

2021-05-10 17:53 UTC, markus-hinsche approved these changes
LGTM

Great refactoring that removes undesired global variables. 
Next, we could copy-paste some refactored functions from cgm-rg and replace them here in the cgm-ml depthmap toolkit

2021-05-10 17:53 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +import functools
We usually order the imports:
- 1st block: python standard libary
- 2nd block: 3rd party libraries
- 3rd block: our own code

Blocks are separated with an empty line usually

2021-05-10 17:53 UTC, markus-hinsche commented on src/common/depthmap_toolkit/pcd2depth.py
> +def process(calibration, pcd_fpath: str, width: int, height: int):
Please provide a type annotation for `calibration` so that if we annotate types, we annotate all of them

2021-05-10 17:53 UTC, markus-hinsche commented on src/common/depthmap_toolkit/toolkit.py
> +    # global calibration
```suggestion
```

2021-05-11 05:52 UTC, lvonasek commented
Those two methods do not work correctly:
* utils.parse_confidence
* utils.convert_2d_to_3d_oriented

branch issue_328:
![Figure_1](https://user-images.githubusercontent.com/6472545/117764990-9b143f80-b22d-11eb-972a-eba330323ae5.png)

branch main:
![Figure_2](https://user-images.githubusercontent.com/6472545/117765000-9e0f3000-b22d-11eb-9361-abd1c3b276fd.png)

test data used:
[huawei_p30pro_240x180.zip](https://github.com/Welthungerhilfe/cgm-ml/files/6456791/huawei_p30pro_240x180.zip)

2021-05-11 05:53 UTC, lvonasek requested changes
These two methods do not work correctly:
* utils.parse_confidence
* utils.convert_2d_to_3d_oriented

branch issue_328:
![Figure_1](https://user-images.githubusercontent.com/6472545/117764990-9b143f80-b22d-11eb-972a-eba330323ae5.png)

branch main:
![Figure_2](https://user-images.githubusercontent.com/6472545/117765000-9e0f3000-b22d-11eb-9361-abd1c3b276fd.png)

test data used:
[huawei_p30pro_240x180.zip](https://github.com/Welthungerhilfe/cgm-ml/files/6456791/huawei_p30pro_240x180.zip)

2021-05-12 06:06 UTC, lvonasek commented
Due to my vacation, I will review it on Monday, I am sorry for taking time on this.

2021-05-17 09:40 UTC, markus-hinsche commented
Great @lvonasek looking forward to your assessment

2021-05-17 09:55 UTC, lvonasek requested changes
Thank you @shanky0009 for the fixes, I am very sorry but I merged another PR in between which will be needed to adjust after updating from main.

Those scripts need to be adjusted:
* convertpcd2depth.py (it crashes right now)
* toolkit.py (the new angle calculation code needs to be adjusted)

2021-05-18 06:51 UTC, lvonasek approved these changes
LGTM

2021-05-18 07:14 UTC, merged