Lvonasek depthmap toolkit segmentation
Welthungerhilfe/cgm-ml pull request #352
Opened 2021-05-31 06:39 UTC by lvonasek

# Description
Detect a floor in depthmap (marked with blue pattern) and the object/child in the depthmap center (marked with yellow pattern). Use this data to calculate object/child height.

![Figure_1](https://user-images.githubusercontent.com/6472545/120150558-7dfadd00-c1eb-11eb-8348-cce01cdd47b7.png)

User story https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1446 (note that this PR is only an example code, not an implementation)

2021-06-02 07:41 UTC, markus-hinsche requested changes
When trying out the functionality, I can observe the logs showing the height. 

I am not yet able to understand the code (I suggested potential improvements in the comments). 

Also there are no unit tests yet, but we write unit tests before merging into main.

Let me know if I can help with any of these issues

2021-06-02 07:41 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +def get_floor_level(width: int, height: int, calibration: List[List[float]], data: bytes, depth_scale: float, max_confidence: float, matrix: list):
Please note that the max line length is 120 characters, see https://github.com/Welthungerhilfe/cgm-ml/blob/main/.flake8

2021-06-02 07:41 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +def get_floor_level(width: int, height: int, calibration: List[List[float]], data: bytes, depth_scale: float, max_confidence: float, matrix: list):
Please add the return type, I guess it is a float according to https://docs.python.org/3/library/statistics.html#statistics.median

2021-06-02 07:41 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +            n = utils.norm(utils.cross(utils.diff(yp, xm), utils.diff(yp, xp)))
What do the variables `v`, `xm`, `xp`, `yp` and `n` mean? Feel free to choose longer variable names to increase readability 

Also you can try to make choose longer variable names (instead of 1 or 2 letters) in the rest of this PR's code

2021-06-02 07:41 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +        n = utils.norm(utils.cross(utils.diff(yp, xm), utils.diff(yp, xp)))
This looks like a duplicate of the code in get_floor_level. This should be a perfect opportunity to extract a separate function

2021-06-02 07:41 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +        if vec[0] > 0 and vec[1] > 1 and vec[0] < width and vec[1] < height and HAS_RGB:
```suggestion
        if 0 < vec[0] < width and 1 < vec[1] < height and HAS_RGB:
```

2021-06-07 08:59 UTC, markus-hinsche reviewed
Some more suggestion for quick improvements. 

As discussed, this is not code that runs in a production setting, so maybe we could maybe skip unit tests for this PR.

2021-06-07 08:59 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +    while (len(stack) > 0):
```suggestion
    while len(stack) > 0:
```

2021-06-07 08:59 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +        if output[pixel[0]][SUBPLOT_SEGMENTATION * height + height - pixel[1] - 1][2] < 0.1:
```suggestion
        index = SUBPLOT_SEGMENTATION * height + height - pixel[1] - 1
        if output[pixel[0]][index][2] < 0.1:
```

This index can be used to shorten below lines. 
Maybe we find a better name then `index`

2021-06-07 08:59 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +            for dir in dirs:
`dir` is a python keyword and should therefore be avoided as variable name

```suggestion
            for direction in dirs:
```

2021-06-07 08:59 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +            highest = point[1]
Suggestion to shorten:
```suggestion
        highest = max(highest, point[1])
```

2021-06-07 08:59 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +        horizontal = ((point[1] - floor) % 0.1) * 10
Why do we do `% 0.1) * 10`?

2021-06-07 08:59 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +    if (depth):
To avoid indentation, you can do 

```python
    if not depth:
        return
    # convert ToF coordinates into RGB coordinates
    ...
```

2021-06-07 09:10 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap.py
> +        horizontal = ((point[1] - floor) % 0.1) * 10
As written in README it is a pattern repeating every 10cm. I was suggesting to ML team to use this as layer to make the model understand metric dimensions of the depthmap.

2021-06-07 09:12 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +        horizontal = ((point[1] - floor) % 0.1) * 10
I suggest to create a variable to make this clearer

```
LENGTH_IN_CM = 10
ABC = 0.1
```

2021-06-07 10:00 UTC, markus-hinsche approved these changes
LGTM

2021-06-07 10:01 UTC, merged