WIP Issue137 write tests in src/common
Welthungerhilfe/cgm-ml pull request #353
Opened 2021-06-01 09:30 UTC by jasminziegler

# Description
Motivation
Fail first fail fast - testing helps us produce less bugs and saves our time in the long run.

Problem
We have a very low test coverage of 19.92% in cgm-ml/src:
Test coverage is the lowest in src/common with 15.72%:

Solution
Write more tests to increase code coverage.
list of functions:
evaluation/evaluation_analysis/QA/eval_depthmap_models/src/evaluate.py
    def copy_dir(src: Path, tgt: Path, glob_pattern: str, should_touch_init: bool = False): 
    def tf_load_pickle(path, max_value): contains another function def py_load_pickle(path, max_value): 
    def prepare_sample_dataset(df_sample, dataset_path): 
src/common/model_utils/preprocessing.py
    def filter_blacklisted_qrcodes(qrcode_paths): 

User story # (US link)
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1258/

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have added tests
- [ ] My Code is review by 1 People

2021-06-21 09:29 UTC, jasminziegler commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    assert (len(dataset_sample) != 0)  # how can I write a better assert statement here?
how can I write a better assert statement here?

2021-06-21 09:49 UTC, markus-hinsche reviewed
I had a quick first glimpse

2021-06-21 09:49 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    assert (len(dataset_sample) != 0)  # how can I write a better assert statement here?
```suggestion
    assert len(dataset_sample), 'There should at least be 1 dataset sample'
```

2021-06-21 09:49 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +REPO_DIR = str(here.parents[6].absolute())
Looks similar to: `CWD = Path(__file__).parent`
We use it in `src/common/evaluation/QA/eval_depthmap_models/eval_main.py`

2021-06-21 09:49 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    ]
These lists seem quite long, can we test the same things with shorter lists?

2021-06-24 13:23 UTC, markus-hinsche requested changes
Lots of work in progress, let's clean up this PR and re-review

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +from evaluation.QA.eval_depthmap_models.src.evaluate import tf_load_pickle  # noqa: E402
```suggestion
from evaluation.QA.eval_depthmap_models.src.evaluate import copy_dir, prepare_sample_dataset, tf_load_pickle  # noqa: E402
```

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    assert temp_common_dir.exists()
This is more specific and therefore tests even more strictly

```suggestion
    assert temp_common_dir.is_dir()
```

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        print("Error: %s : %s" % (temp_common_dir, e.strerror))
What does this test? 

If you need a teardown functionality, here is how you could implement this: https://stackoverflow.com/questions/26405380/how-do-i-correctly-setup-and-teardown-for-my-pytest-class-with-tests

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        "100",  # --> should be removed, right? bec sample 1 artifact per scan
Please remove the questions, feel free to use github for discussions

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +
Please remove debug code from tests
```suggestion
```

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    assert (len(dataset_sample) == 3), 'There should be 3 samples in the dataset'
```suggestion
    assert len(dataset_sample) == 3, 'There should be 3 samples in the dataset'
```

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    IMAGE_TARGET_WIDTH = 180
local variables should be lowercase

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +                                                        == IMAGE_TARGET_WIDTH)
```suggestion
    assert type(test_image) == tuple
    assert test_image[1].shape[0] == IMAGE_TARGET_HEIGHT 
    assert test_image[1].shape[1] == IMAGE_TARGET_WIDTH
```

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    assert (type(test_image)
Please use `isinstance(obj, type)`

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        exception_caught = True
Please use the `with pytest.raises` context manager

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        print("hey")
Before assigning the PR to a review, please clean up the code. 
Clean code does not include debug prints.

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +    assert False"""
```suggestion
```

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/model_utils/tests/test_preprocessing_blacklist.py
> +]
I think we don't need the comments in the tests data, maybe they don't even apply

2021-06-24 13:23 UTC, markus-hinsche commented on src/common/model_utils/tests/test_preprocessing_blacklist.py
> +    qrcode_paths_wrong.append(qrcode_path)
This global code might belong into a function

2021-06-28 09:00 UTC, jasminziegler commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        print("Error: %s : %s" % (temp_common_dir, e.strerror))
This removes the dir and catches exceptions that might be thrown. I read this is a good practice to catch exceptions when deleting a folder. I don't really understand why the solution in your link is better.

2021-06-28 11:36 UTC, jasminziegler commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +from evaluation.QA.eval_depthmap_models.src.evaluate import tf_load_pickle  # noqa: E402
I get a "line too long" error here.

2021-06-28 12:31 UTC, jasminziegler commented on src/common/model_utils/tests/test_preprocessing_blacklist.py
> +"""def prepare_empty_qrs():
This throws an error 
"for qrcode_path in qrcode_paths:
E       TypeError: 'NoneType' object is not iterable" in preprocessing.py

So this means the function is not prepared for receiving empty qr code path lists, am I correct?

2021-06-28 12:33 UTC, jasminziegler commented
Dear @markus-hinsche, 
thanks for your first review! Sorry for the chaos, I tried my best this time to clean everything up and integrate your change requests. I left a comment where things were still unclear or need discussion. Thanks!

2021-06-28 12:48 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        print("Error: %s : %s" % (temp_common_dir, e.strerror))
The solution in the link is the standard way of doing this. The concept of cleaning up after the test is called "teardown". Doing things the standard way is often easier to understand by fellow engineers how will maintain the code

2021-06-28 12:48 UTC, markus-hinsche commented on src/common/model_utils/tests/test_preprocessing_blacklist.py
> +    QRCODES_11SAMPLES = [
```suggestion
    qrcodes_samples = [
```

Please also make other local variables below lowercase, as this is our convention

2021-06-28 12:48 UTC, markus-hinsche commented on src/common/model_utils/tests/test_preprocessing_blacklist.py
> +    assert str(e.value) == "1585360775-fa64muouelXXXX"  # first wrong qrcode
Try to use assert message instead of comment

```suggestion
    assert str(e.value) == "1585360775-fa64muouelXXXX", "first wrong qrcode"
```

2021-06-28 12:48 UTC, markus-hinsche commented on src/common/model_utils/tests/test_preprocessing_blacklist.py
> +"""def prepare_empty_qrs():
Yes, when testing, it often turns out that the function under test is not actually doing the right thing. 

How to proceed in such a case:
- write a test that fails (you did this)
- implement the correct behavior
- check that the test passes

2021-06-30 09:32 UTC, jasminziegler commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        print("Error: %s : %s" % (temp_common_dir, e.strerror))
Thanks for your patience with me here and for explaining @markus-hinsche ! I am learning a ton everyday, that's great. 
Finally understood some of the pytest fixtures, too. Hopefully I implemented it correctly!

Only thing I am still wondering about and can't find clarity: do I still need exception handling for the yield functionality?
What I learnt from my research online: if the setup code (before yield) raises an exception, the teardown code (after yield) is not executed. 
What if the teardown code itself raises an exception?

2021-06-30 09:49 UTC, markus-hinsche commented on src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py
> +        print("Error: %s : %s" % (temp_common_dir, e.strerror))
Using `yield` seems to be the correct way to cleanup(teardown) in pytest.

> do I still need exception handling for the yield functionality?

Not sure, but a test should definitely: 
- test a unit
- clean up after itself (both when the unit fails or succeeds)

> What if the teardown code itself raises an exception?

I hope I understand the question correctly. The teardown code should be written in a way that it doesn't throw an exception

2021-06-30 15:27 UTC, jasminziegler reviewed
selfreview performed

2021-06-30 15:34 UTC, markus-hinsche approved these changes
LGTM! Thanks for the contribution :)

2021-06-30 15:37 UTC, merged