WIP couldnt find all datasets, in clarification with team
Welthungerhilfe/cgm-ml pull request #370
Opened 2021-06-08 15:21 UTC by jasminziegler

# Description

Issue #336 round(age) has been exchanged with flore(age)
Now we want to run all EDA notebooks to have the updated age in years figures.

User story #336

# How Has This Been Tested?
ran notebook and checked age calculations for some datapoints

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] My Code is review by 1 People

2021-06-08 15:21 UTC, jasminziegler commented
issue with datasets, in clarification with team

2021-06-08 15:22 UTC, jasminziegler commented on src/data_utils/dataset_EDA/anon-depthmap-testset/EDA_anon-depthmap-testset.ipynb
>   "cells": [
<p>that's funny that now it is not colorful anymore. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Welthungerhilfe/cgm-ml/pull/370/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2021-06-10 08:31 UTC, jasminziegler commented
Shanky migrated datasets today, are all available now with new connection file format that was created to prevent datasets from vanishing. I wrote down all the steps I had to do to gather all information needed for the new connection file and sent that to Shanky. He will soon add this to the wiki.

2021-06-10 10:19 UTC, jasminziegler commented
ran all notebooks successfully except for rgbd5k, labels folder and scans.csv file missing. in clarification with team

2021-06-11 14:51 UTC, markus-hinsche requested changes
Please undo the changes to `src/data_utils/dataset_EDA/anon-rgbd-5k/EDA_anon-rgbd-5kscans.ipynb` since we would keep the rough information about this dataset. 

After this, we can merge

2021-06-14 09:49 UTC, merged