Endpoint deployment
Welthungerhilfe/cgm-ml pull request #372
Opened 2021-06-11 07:10 UTC by prajurock

# Description

Endpoint deployment of model for easy deployment 

[](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1311)

# How Has This Been Tested?

Test.py added

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2021-06-14 08:11 UTC, markus-hinsche requested changes
It will be very nice if this really works this is a great achievement.

I tried to run `check.py` locally, but there is no depthmap file provided that I could use. Therefore I can't verify if this code works. 

There are no unit tests. Please test your code.

2021-06-14 08:11 UTC, markus-hinsche commented on src/common/endpoints/entry_script_aci.py
> +def run(data):
Could we add type annotations for `data` and the return type

2021-06-14 08:11 UTC, markus-hinsche commented on src/common/endpoints/Readme.md
> +* Deploy your model locally  by running `deploy.py`
```suggestion
* Deploy your model locally by running `deploy.py`
```

2021-06-14 08:11 UTC, markus-hinsche commented on src/common/endpoints/Readme.md
> +* Deploy your model locally  by running `deploy.py`
`deploy.py` doesn't exist. Should this be `deploy_endpoint.py`?

2021-06-14 08:11 UTC, markus-hinsche commented on src/common/endpoints/Readme.md
> +* Deploy your model locally  by running `deploy.py`
> locally

This seems to work for locally and on Azure? Should we remove `locally` from the explanation?

2021-06-14 08:11 UTC, markus-hinsche commented on src/common/endpoints/config.py
> +from bunch import Bunch
Should we make one config_deep_ensemble.py local to be able check this locally? Can we add a `TEST_FILE` that actually exists(e.g. depthmap file in `testdata/` that we also use for unit tests)?

2021-06-14 08:15 UTC, prajurock commented on src/common/endpoints/config.py
> +    TEST_FILE=''
I use my local test file. Anyone can use any local test file.

2021-06-14 08:16 UTC, prajurock commented on src/common/endpoints/config.py
> +from bunch import Bunch
Yes. I planned to do that if I add more endpoints

2021-06-14 08:37 UTC, markus-hinsche commented on src/common/endpoints/config.py
> +    TEST_FILE=''
We now have some depthmaps in the codebase for testing purposes `src/common/depthmap_toolkit/tests/huawei_p40pro`
We could provide this in the config as a default, so everybody can just try it out directly (without having to search/ask for a sample depthmap)

2021-06-14 11:47 UTC, markus-hinsche commented on src/common/endpoints/config.py
> +CONFIG = Bunch(dict(
Good point, I see only 1 RUN_ID, but I thought there are 16 models

2021-06-16 04:43 UTC, prajurock commented on src/common/endpoints/Readme.md
> +* If Test is successful deploy model into ACI
run deploy_endpoint script

2021-06-16 04:43 UTC, prajurock commented on src/common/endpoints/config.py
> +    MODEL_NAME="Deepensemble",
okay

2021-06-16 10:00 UTC, prajurock commented on src/common/endpoints/config.py
> +CONFIG = Bunch(dict(
Yes. One run id in one endpoint.
16 endpoints for deep ensemble

2021-06-16 10:52 UTC, shanky0009 approved these changes

2021-06-16 12:15 UTC, markus-hinsche commented on src/common/endpoints/check.py
> +sys.path.append('./src/common/data_utilities')  # noqa
This file will only work if we are in the `cgm-ml`/REPO_DIR folder, because the import is absolute. 
Can we make it work no matter from where it is executed?

2021-06-16 19:23 UTC, markus-hinsche commented on src/common/endpoints/config_deepensemble_1.py
> +               REPO_DIR / 'src/common/depthmap_toolkit/tests/static_files/4ed427b5-3fd9-4f4d-8e58-19e39c7d77b6']
I would prefer plural when a list of things follows

```suggestion
    TEST_FILES=[REPO_DIR / 'src/common/depthmap_toolkit/tests/static_files/4ed427b5-3fd9-4f4d-8e58-19e39c7d77b6',
               REPO_DIR / 'src/common/depthmap_toolkit/tests/static_files/4ed427b5-3fd9-4f4d-8e58-19e39c7d77b6']
```

2021-06-16 19:23 UTC, markus-hinsche commented on src/common/endpoints/READMEs.md
> +    VERSION= Registered Model version Number,
```suggestion
    VERSION=Registered Model version Number,
```

2021-06-16 19:23 UTC, markus-hinsche commented on src/common/model_utils/environment.py
> +
```suggestion
```

2021-06-22 06:49 UTC, merged