Depthmap - faceblur added
Welthungerhilfe/cgm-ml pull request #377
Opened 2021-06-21 06:50 UTC by lvonasek

# Description

Faceblur of the detected standing child added. It uses the highest point of the child and blur all pixels in distance less than 25cm.
![faceblur](https://user-images.githubusercontent.com/6472545/122718767-9b145000-d26d-11eb-8ce9-491faf341b48.png)

# How Has This Been Tested?

Visual test on multiple input data

2021-06-21 08:02 UTC, markus-hinsche requested changes
It is good to try some alternative face blurring approach.

I tried to run this but can't verify if this works.

2021-06-21 08:02 UTC, markus-hinsche commented on src/common/depthmap_toolkit/visualisation.py
> +                            count = count + 1
If pixel would be a numpy array (like input), this could be simplified
```suggestion
                            pixel = pixel + input[tx][index]
                            count = count + 1
```

2021-06-21 08:02 UTC, markus-hinsche commented on src/common/depthmap_toolkit/visualisation.py
> +def blur_face(input: np.array, highest: list, dmap: Depthmap) -> np.array:
I am not sure if I understand how this approach works. Do we just blur the upper 25% of a detected object? 
Can you describe the approach/algorithm high-level in the docstring?

2021-06-21 08:20 UTC, lvonasek commented on src/common/depthmap_toolkit/visualisation.py
> +    output[x][index][0] = dmap.rgb_array[y][x][0] / 255.0
Fixed, there was missing hasrgb flag

2021-06-21 08:22 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap_utils.py
> +def len(v: list) -> float:
rename to length to keep the utils class convention

2021-06-21 08:23 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap.py
>  import statistics
This is not the code of this PR.

2021-06-21 08:28 UTC, lvonasek commented on src/common/depthmap_toolkit/visualisation.py
> +    logging.info('height=%fm', highest[1] - floor)
fixed the wrong float information

2021-06-21 08:42 UTC, lvonasek commented on src/common/depthmap_toolkit/visualisation.py
> +def blur_face(input: np.array, highest: list, dmap: Depthmap) -> np.array:
Docstring added

2021-06-21 08:45 UTC, lvonasek commented on src/common/depthmap_toolkit/visualisation.py
> +                        if tx > 0 and ty > 0 and tx < dmap.width and ty < dmap.height:
I do not see such an example

2021-07-05 06:12 UTC, lvonasek commented
Hi @markus-hinsche, would you find time to help me with the unit tests? I do not see way how to implement them.

2021-07-05 09:33 UTC, markus-hinsche approved these changes
LGTM 🔥

2021-07-05 09:34 UTC, merged