Depthmap segmentation improvement
Welthungerhilfe/cgm-ml pull request #401
Opened 2021-07-09 08:18 UTC by lvonasek

# Description

Our depthmap segmentation had several issues:
* the object/child was not detected if it wasn't in the center
* the mask contain on floor undetected pixels which causes spoiling of seed algortihm
* the formula for connected pixels got broken by the code review

This PR solves the issue above by:
* marking undefined data in depthmap in mask as MASK_INVALID
* do not smooth invalid and valid depth data
* detect all objects covering at least 25% of the screen (width / 4) and select the most focused one

![segmentation](https://user-images.githubusercontent.com/6472545/125045035-dcde2c80-e09c-11eb-91bb-806c170a62a6.png)

# How Has This Been Tested?

Visual test on data from 5 devices with different objects (puppy, chair, ...) and different device poses (angle, focus, distance)

2021-07-09 10:30 UTC, markus-hinsche requested changes

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +        closest = 9999999
sys.maxsize

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +            d = segment[1][3] - int(self.height / 2)
Use numpy array operations instead of for-loop (this code will be faster and shorter)

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +                    mask[x][y] = MASK_CHILD
Use numpy operations instead of for-loops

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +                aabb = [pixel[0], pixel[1], pixel[0], pixel[1]]
Find a semantically meaningful variable name instead of `aabb`

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +                        aabb[3] = pixel[1]
You can use this shortcut, which does the same I think
```suggestion
                    aabb[3] = max(aabb[3], pixel[1])
```

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +                        aabb[3] = pixel[1]
This code looks repetitive. Consider using numpy or a for-loop

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +                if (object_size_pixels > self.width / 4):
```suggestion
                if object_size_pixels > self.width / 4:
```

2021-07-09 10:30 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +            return 0
```suggestion
        if 0 in [depth_center, depth_x_plus, depth_y_minus, depth_y_plus]:
            return 0
```

2021-07-13 05:31 UTC, prajurock commented on src/common/depthmap_toolkit/depthmap.py
> +                aabb = [pixel[0], pixel[1], pixel[0], pixel[1]]
Not changing as stated by Lubos

2021-07-13 06:49 UTC, prajurock commented on src/common/depthmap_toolkit/depthmap.py
> +            d = segment[1][3] - int(self.height / 2)
Array size is very small. So i am skipping this step

2021-07-13 14:11 UTC, prajurock commented on src/common/depthmap_toolkit/depthmap.py
> +                        aabb[3] = pixel[1]
I think using for loop will only make code complex

2021-07-13 14:49 UTC, lvonasek commented
aabb[0] = min(pixel[0], aabb[0])
aabb[1] = min(pixel[1], aabb[1])
aabb[2] = max(pixel[0], aabb[2])
aabb[3] = max(pixel[1], aabb[3])

Other changes looks okay

2021-07-14 07:06 UTC, markus-hinsche approved these changes
LGTM

I added a few suggestions that you could do before merging

2021-07-14 07:06 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +                        aabb[2] = pixel[0]
Consider the shortcut
```suggestion
                    aabb[3] = max(aabb[3], pixel[1])
```

2021-07-14 07:06 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +                current = current - 1
This function is quite long. 
Can we split it into multiple functions?

2021-07-14 07:06 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +        # Get all neightbor depths
```suggestion
        # Get all neighbor depths
```

2021-07-15 06:43 UTC, merged