WIP Refactor Depthmap class for RGBD
Welthungerhilfe/cgm-ml pull request #406
Opened 2021-07-19 13:14 UTC by markus-hinsche

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

User story # (US link)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2021-07-19 16:30 UTC, lvonasek commented
I will check it detaily when I am back from vacation (Thursday). Please do not merge it, there are q few things which need to be changed.

2021-07-21 15:00 UTC, markus-hinsche commented
I am currently working on speeding this up because the for loops over all pixels take quite long for me (4 to 20 seconds per depthmap for the more advanced operations that have to be done per pixel). 

@lvonasek You can already review the changes in this PR, but please don't make commits into this branch, as I have uncommitted/unfinished work which is based on this.

2021-07-22 05:33 UTC, lvonasek requested changes
Here is a change of the behavior, Z-axis has a different coordinate system in comparison with the previous version.
```
        res = [-res[0], res[1], res[2]]
        if is_google_tango_resolution(self.width, self.height):
            res = [-res[0], -res[1], -res[2]]
```

Do not use try and catch for index error, fix the if statements instead
```
        if tx - 1 < 0 or ty - 1 < 0:
            return 0.
        if tx + 1 >= self.width or ty + 1 >= self.height:
            return 0.

        # Get all neighbor depths
        try:
            depth_center = self.depthmap_arr[tx, ty]
            depth_x_minus = self.depthmap_arr[tx - 1, ty]
            depth_x_plus = self.depthmap_arr[tx + 1, ty]
            depth_y_minus = self.depthmap_arr[tx, ty - 1]
            depth_y_plus = self.depthmap_arr[tx, ty + 1]
        except IndexError:
            return 0.
```

2021-07-23 07:09 UTC, markus-hinsche commented on src/common/depthmap_toolkit/depthmap.py
> +            res = [-res[0], -res[1], -res[2]]
```suggestion
            res = [-res[0], -res[1], res[2]]
```

2021-07-26 08:05 UTC, lvonasek approved these changes
LGTM

2021-07-26 09:22 UTC, merged