Evaluation of depthmap toolkit CV height estimation
Welthungerhilfe/cgm-ml pull request #426
Opened 2021-08-03 13:03 UTC by lvonasek

# Description

As a necessary step, this PR updates depthmap toolkit:
* improving segmentation by not including children feet (segmentation spilled out there)
* detecting boundaries and validating if the children is fully visible (it is when the boundary do not touch the data border)
* extrapolation of the child's highest point (very often set lower due to not detected hair in the depthmap)
![good_one](https://user-images.githubusercontent.com/6472545/128019024-d0ffd4f0-ce7c-4be1-b03f-c9d384fb2b56.png)

The extrapolation is done using edge detection (finding the edge above the highest point from depthmap)
![depthmapToolkitViz](https://user-images.githubusercontent.com/6472545/128019660-2075d564-9296-4e9d-91ff-13e307eb3b56.jpg)

The evaluation filters data where:
* child is lying (not supported at the moment)
* data is captured by Lenovo Phab 2 Pro (low quality data)
* child is not fully visible

User story https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1446

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] My Code is review by 1 People

2021-08-06 11:06 UTC, markus-hinsche requested changes
Thanks for the nice additions. Looks really good, but it is also a lot of code added, therefore it is also a lot of review comments.

When reviewing, I was a bit stricter with `src/common/depthmap_toolkit` because this is used by multiple people/components and therefore shouldn't break and should be re-usable. 

When reviewing `src/common/evaluation/CV`, I was less strict, because this is new code and we don't know if we end up re-using this.

2021-08-06 11:06 UTC, markus-hinsche commented on src/common/evaluation/CV/evaluation.py
> +    path = 'C:/Users/VonasekLu/Downloads/raw_dataset/'
This will not work for other people. Please adjust so that other team members can use this as well

2021-08-06 11:06 UTC, markus-hinsche commented on src/common/evaluation/CV/evaluation.py
> +        if height < 45:
45 seems to be some threshold that we could tune.
Please put this into a global variable with a meaningful name.

2021-08-06 11:06 UTC, markus-hinsche commented on src/common/evaluation/CV/rgbd_match.py
> +METADATA_EXTENSION = 4
This variable seem to be redefined. I suggest to use a shared constants file

2021-08-06 11:06 UTC, markus-hinsche commented on src/common/evaluation/CV/rgbd_match.py
> +    metadata_file = 'metadata.csv'
Can you provide instructions how to run/use `src/common/evaluation/CV`? 
I don't yet understand where metadata.csv comes from or how I should use it. 

A README.md in `src/common/evaluation/CV/` could alleviate this concern.

2021-08-06 11:33 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap.py
> +        if count > 0:
I tried to use numpy array but I failed to make it working correctly

2021-08-06 11:35 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap_utils.py
> +    aabb.append(np.max(ybig))
That would not work, the order of operations is important there.

For min xbig[cond], ybig[cond] has to have the original value.
For max xbig[cond], ybig[cond] has to be zero.

2021-08-06 11:37 UTC, lvonasek commented on src/common/depthmap_toolkit/visualisation.py
> +            output[x, index] = get_smoothed_pixel(data, x, index, 5)
No, depthmap_arr_smooth is a depth information. I am smoothing here the RGB information.

2021-08-06 11:47 UTC, lvonasek commented on src/common/depthmap_toolkit/visualisation.py
> +    y2 = height - aabb[1] - 1
height is 180
aabb[1] and aabb[3] is from 0 to 179
we want that y1 and y2 is from 0 to 179

check min and max value:
179 = 180 - 0 - 1
0 = 180 - 179 - 1

2021-08-06 12:11 UTC, markus-hinsche commented on src/common/depthmap_toolkit/visualisation.py
> +            output[x, index] = get_smoothed_pixel(data, x, index, 5)
Ahh understood.
Would it make sense to align this though? To also calculate the smoothed RGB array with np.array's instead of for-loops and also running it for the entire array a single time

2021-08-06 12:13 UTC, lvonasek commented on src/common/depthmap_toolkit/visualisation.py
> +        highest_point = dmap.get_extrapolated_highest_point(edges, mask)
No, the updated highest_point brings no improvement on face blurring

2021-08-06 12:33 UTC, lvonasek commented on src/common/evaluation/CV/rgbd_match.py
> +METADATA_EXTENSION = 4
That are different variables. Rudra provided me the metadata in a wrong format, this script is reformating it into correct format. This metadata columns are in this file different.

2021-08-06 12:51 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap.py
> +    def calculate_edges_array(self) -> np.ndarray:
Function removed.

2021-08-06 12:51 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap.py
> +    def get_extrapolated_highest_point(self, edges: np.ndarray, mask: np.ndarray) -> np.ndarray:
Function removed.

2021-08-06 12:52 UTC, lvonasek commented on src/common/depthmap_toolkit/depthmap.py
> +        np.clip(output, 0., 1., output)
Function removed.

2021-08-10 08:32 UTC, markus-hinsche approved these changes
LGTM

I checked that toolkit.py still runs as expected

I left some easy suggestions for the new code that I hadn't seen in my last review

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/depthmap_toolkit/depthmap.py
> +        margin = max(self.width, self.height) / 20
`20` seems to be some threshold that we could tune.
Please put this into a global variable with a meaningful name.

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/depthmap_toolkit/tests/test_depthmap_toolkit_utils.py
> +    ])
This should be equivalent

```suggestion
    rgb = np.zeros((5, 5, 3))  # black
    rgb[2, 2] = 1.  # white
```

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/README.md
> +You can browse the data using Microsoft Azure Storage Explorer under cgm-in-bmz-sub/cgmbeciinbmzsa/Blob Containers/cgm-raw.
```suggestion
You can browse the data using Microsoft Azure Storage Explorer under `cgm-in-bmz-sub/cgmbeciinbmzsa/Blob Containers/cgm-raw`.
```

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/README.md
> +Open Cloudbeaver (https://cgm-core-infra-prod-ci-sqlmgmt.azurewebsites.net/#/) and run following SQL query:
```suggestion
Open Cloudbeaver <https://cgm-core-infra-prod-ci-sqlmgmt.azurewebsites.net/#/> and run following SQL query:
```

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/README.md
> +Note that setting up the download process take about 2hours and downloading more than 60h.
```suggestion
Note that setting up the download process takes about 2hours and downloading takes more than 60h.
```

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/README.md
> +I used the filter function to limit the downloaded amounts (the current size of the raw data is 17.5GB)
```suggestion
You can use the filter function to limit the downloaded amounts (the current size of the raw data is 17.5GB)
```

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/README.md
> +# Setting up the environment
```suggestion
# Computer vision

## Setting up the environment
```

2021-08-10 08:32 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/README.md
> +# Using the evaluation system
```suggestion
## Using the evaluation system
```

2021-08-10 08:34 UTC, lvonasek commented on cgmml/common/depthmap_toolkit/depthmap.py
> +from cgmml.common.depthmap_toolkit.depthmap_utils import calculate_boundary
Unfortunatelly not (flake8 compains that it is more than 120 characters per line)

2021-08-10 08:39 UTC, markus-hinsche commented on cgmml/common/depthmap_toolkit/depthmap.py
> +from cgmml.common.depthmap_toolkit.depthmap_utils import calculate_boundary
```suggestion
from cgmml.common.depthmap_toolkit.depthmap_utils import (
    matrix_calculate, IDENTITY_MATRIX_4D, parse_numbers, calculate_boundary)
```

2021-08-10 08:47 UTC, merged