Median CV evaluation
Welthungerhilfe/cgm-ml pull request #482
Opened 2021-09-09 08:57 UTC by lvonasek

# Description

This PR updates CV evaluation to use all scan artifacts and calculate median of height results. This improved accuracy for 1.2cm by about 5% and compute time decreased 12x.

![median](https://user-images.githubusercontent.com/6472545/132654646-ffc975a5-0ab7-4d15-9d41-436c18cd7c6b.png)

2021-09-09 09:42 UTC, markus-hinsche requested changes
The result of this PR seems promising. It seems like a big improvement to use the median angle and median height.

The PR description mentions that the compute time decreased 12x. Can you explain why this happens?

2021-09-09 09:42 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +        if one_artifact_per_scan & (int(data[METADATA_ORDER]) != 1):
and

2021-09-09 09:42 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +    if math.isnan(height):
I think this if statement should be checked before `MINIMUM_CHILD_HEIGHT_IN_CM` and `MAXIMUM_CHILD_HEIGHT_IN_CM`

2021-09-09 09:42 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +        error = abs(height - float(data[METADATA_MANUAL_HEIGHT]))
This code seems quite long. I suggest to split this up into functions and have only a minimum amount of code in if the section `if  __name__ == "__main__":`

2021-09-09 09:42 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +        error = abs(height - float(data[METADATA_MANUAL_HEIGHT]))
We have write unit tests for this logic, right?

2021-09-09 09:42 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +    for key in keys:
If you increase an index in every loop iteration, this is how you can do it in Python:

```suggestion
    index = 0
    for key_index, key in enumerate(keys):
```

2021-09-09 09:42 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +    indata = filter_metadata(read_csv(metadata_file), is_standing, False)
I don't understand what `indata` is.
Can we rename `indata` to something more semantically meaningful?

2021-09-09 09:46 UTC, lvonasek commented
@markus-hinsche 
Processing front and back scans is 8x slower because it is 8x more artifacts.
Processing 360 scans is 24x slower because it is 24x more artifacts.
Per scan in average it is (8+8+24)/3=12 more artifacts

2021-09-09 09:51 UTC, lvonasek commented on cgmml/common/evaluation/CV/evaluation.py
> +        error = abs(height - float(data[METADATA_MANUAL_HEIGHT]))
no, we did not

2021-09-09 09:56 UTC, markus-hinsche commented
I think you mean that before this PR you only analyzed the first artifact of each scan. 
No we are 12x slower because we process all artifacts of a scan. 

Can you confirm if these statements are correct?

2021-09-09 09:57 UTC, lvonasek commented
> I think you mean that before this PR you only analyzed the first artifact of each scan.
> No we are 12x slower because we process all artifacts of a scan.
> 
> Can you confirm if these statements are correct?

Yes, the statements are correct

2021-09-09 10:16 UTC, markus-hinsche requested changes
This PR is not yet unit tested.

2021-09-09 10:16 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +            output[key] = []
To avoid the 2 lines of code, please use a Python [defaultdict](https://docs.python.org/3/library/collections.html#collections.defaultdict)

```suggestion
        if not output.get(key):
            output[key] = []
```

2021-09-09 10:16 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
>          raise Exception(exc)
Instead of:
```
    # Check if the input was not rejected
    try:
        height, angle = predict_height(depthmap_file, rgb_file, calibration_file)
    except Exception as exc:
        raise Exception(exc)
```

you can write:
```
    # Check if the input was not rejected
    height, angle = predict_height(depthmap_file, rgb_file, calibration_file)
```

This should be equivalent

2021-09-09 10:16 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +        logger.info('Processing %d/%d', key_index + 1, size)
Optional suggestion: Could be simplified to:
```suggestion
    for key in tqdm(keys):
```

2021-09-09 10:16 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +def run_evaluation(metadata: dict, calibration_file: str):
I don't understand what `metadata` is. Could you give an example when describing the parameters in a docstring.

2021-09-09 10:16 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +        avg_err += error
```suggestion
        sum_err += error
```

2021-09-09 10:16 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +        info = 'Average error=' + str(avg_err / float(len(output))) + 'cm'
```suggestion
        avg_err = sum_err / len(output)
        info = f'Average error={avg_err}cm'
```

2021-09-09 10:16 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/evaluation.py
> +        error = abs(height - float(data[METADATA_MANUAL_HEIGHT]))
Let's write unit tests then

2021-09-09 11:12 UTC, lvonasek commented on cgmml/common/evaluation/CV/evaluation.py
> +        logger.info('Processing %d/%d', key_index + 1, size)
tqdm on my system really breaks the logging,it is hard to read it. I will avoid using it

2021-09-10 07:40 UTC, markus-hinsche approved these changes
LGTM

I really like this is tested right now. The docstrings are very helpful for me, now I can understand what the units in the code is doing

2021-09-10 07:40 UTC, markus-hinsche commented on cgmml/common/evaluation/CV/tests/test_evaluation.py
> +        assert True
This can also be done with https://docs.pytest.org/en/stable/reference.html?highlight=raises#pytest.raises
```
def test_fails_without_info():
    with pytest.raises(Exception):
        x = 1 / 1
```

2021-09-10 07:43 UTC, merged